#ifndef _SMART_IOS_ERROR_H_
#define _SMART_IOS_ERROR_H_
#pragma once
//////////////////////////////////////////////////////////////////////////
#define	IOS_ERROR_TYPE_MIRROR						1
#define	IOS_ERROR_TYPE_QUERY						2

#define	IOS_ERROR_SUCCESS							0
#define	IOS_ERROR_DEVICE_NEED_REPLUG				1
#define	IOS_ERROR_DEVICE_NEED_RESTART				2
#define	IOS_ERROR_DEVICE_NEED_PAIR					3

#define	IOS_ERROR_OBJECT_NOT_CREATED				1001
#define	IOS_ERROR_OBJECT_NOT_INITED					1002
#define	IOS_ERROR_OBJECT_IS_EMPTY					1003

#define	IOS_ERROR_THREADPOOL_NOT_CREATED			2001
#define	IOS_ERROR_THREADPOOL_NOT_INITED				2002

#define	IOS_ERROR_LICENSE_NOT_CREATED				9001
#define	IOS_ERROR_LICENSE_NOT_INITED				9002
#define	IOS_ERROR_LICENSE_FILE_NOT_FOUND			9003
#define IOS_ERROR_LICENSE_OBJECT_CORRUPT			9004
#define	IOS_ERROR_LICENSE_FILE_CORRUPT				9005
#define	IOS_ERROR_LICENSE_STATUS_NOT_MATCHED		9006
#define IOS_ERROR_LICENSE_PASSWORD_EMPTY			9007
#define	IOS_ERROR_LICENSE_PASSWORD_NOT_MATCHED		9008
#define	IOS_ERROR_LICENSE_EXPIRED					9009
#define	IOS_ERROR_LICENSE_INVALIDTED				9010
#define	IOS_ERROR_LICENSE_EXCEEDING_QUANTITY		9011

#define	IOS_ERROR_DEVICE_LIST_NOT_CREATED			0xC001
#define	IOS_ERROR_DEVICE_LIST_NOT_INITED			0xC002
#define	IOS_ERROR_DEVICE_ENUMERATOR_NOT_CREATED		0xC003
#define	IOS_ERROR_DEVICE_ENUMERATOR_NOT_INITED		0xC004

#define IOS_ERROR_DEVICE_CONSUMER_IS_EMPTY							0xD001
#define IOS_ERROR_DEVICE_CONSUMER_AUDIO_QUEUE_EVENT_NOT_CREATED		0xD002
#define IOS_ERROR_DEVICE_CONSUMER_VIDEO_QUEUE_EVENT_NOT_CREATED		0xD003
#define IOS_ERROR_DEVICE_CONSUMER_AUDIO_TASK_EVENT_NOT_CREATED		0xD004
#define IOS_ERROR_DEVICE_CONSUMER_VIDEO_TASK_EVENT_NOT_CREATED		0xD005
#define	IOS_ERROR_DEVICE_CONSUMER_AUDIO_TASK_NOT_CREATED			0xD006
#define	IOS_ERROR_DEVICE_CONSUMER_VIDEO_TASK_NOT_CREATED			0xD007

#endif // _SMART_IOS_ERROR_H_